# docker-compose.yml file

# docker-compose version
version: '3'

# List of volumes
volumes:
  pg_data:

# List of containers
services:
  # This is a DB container
  db:
    image: postgres:13.10
    container_name: mpg_calculator_db
    env_file: .env
    # Which volume to attach to this container
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app_network
  # Name and description of the container with the backend
  bot:
    # From which Dockerfile to build the image for this container:
    build: .
    container_name: mpg_calculator_bot
    env_file: .env
    ## Which containers need to be started before this container starts:
    depends_on:
      - db
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
