# Файл docker-compose.yml

# Версия docker-compose
version: '3'

# Перечень volume
volumes:
  pg_data:

# Перечень контейнеров
services:
  # Имя и описание первого контейнера; имя выбирает разработчик. 
  # Это контейнер БД
  db:
    # Из какого образа запустить контейнер:
    image: postgres:13.10
    container_name: mpg_calculator_db
    # Файл (или список файлов) с переменными окружения
    env_file: .env
    # Какой volume подключить для этого контейнера
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app_network
  # Имя и описание контейнера с бэкендом
  bot:
    # Из какого Dockerfile собирать образ для этого контейнера:
    build: .
    container_name: mpg_calculator_bot
    env_file: .env
    # Какие контейнеры нужно запустить до старта этого контейнера:
    depends_on:
      - db
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
