# Generated by Django 5.1.4 on 2025-01-15 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Refuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('fuel_amount', models.FloatField()),
                ('odometer_reading', models.FloatField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram_bot.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='MPGCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField()),
                ('fuel_used', models.FloatField()),
                ('mpg', models.FloatField()),
                ('refuel_end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_refuel', to='telegram_bot.refuel')),
                ('refuel_start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_refuel', to='telegram_bot.refuel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram_bot.useraccount')),
            ],
        ),
    ]
